# Generated by Django 3.0.8 on 2020-07-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BeetSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlyThickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WaterProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Godown')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.PlySize')),
                ('thickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.PlyThickness')),
            ],
        ),
        migrations.CreateModel(
            name='Plywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Godown')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.PlySize')),
                ('thickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.PlyThickness')),
            ],
        ),
        migrations.CreateModel(
            name='Beet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Godown')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BeetName')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BeetSize')),
            ],
        ),
    ]
