# Generated by Django 3.0.8 on 2020-07-02 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_beet_beetname_beetsize_plysize_plythickness_plywood_waterproof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plythickness',
            options={'verbose_name': 'Ply Thickness', 'verbose_name_plural': 'Ply Thickness'},
        ),
        migrations.AddField(
            model_name='others',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/uploads/others'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beetname',
            name='image',
            field=models.ImageField(upload_to='media/uploads/beet'),
        ),
        migrations.AlterField(
            model_name='plythickness',
            name='image',
            field=models.ImageField(upload_to='media/uploads/ply'),
        ),
    ]
