# Generated by Django 3.0.8 on 2020-07-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200702_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beet',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='beet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='beet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='others',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='plywood',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='plywood',
            name='size',
        ),
        migrations.RemoveField(
            model_name='plywood',
            name='thickness',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='waterproof',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='waterproof',
            name='size',
        ),
        migrations.RemoveField(
            model_name='waterproof',
            name='thickness',
        ),
        migrations.DeleteModel(
            name='Beet',
        ),
        migrations.DeleteModel(
            name='BeetName',
        ),
        migrations.DeleteModel(
            name='BeetSize',
        ),
        migrations.DeleteModel(
            name='Godown',
        ),
        migrations.DeleteModel(
            name='Others',
        ),
        migrations.DeleteModel(
            name='PlySize',
        ),
        migrations.DeleteModel(
            name='PlyThickness',
        ),
        migrations.DeleteModel(
            name='Plywood',
        ),
        migrations.DeleteModel(
            name='WaterProof',
        ),
    ]
