# Generated by Django 3.0.8 on 2020-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_beet_beetname_beetsize_godown_others_plysize_plythickness_plywood_product_waterproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beetname',
            name='image',
            field=models.ImageField(upload_to='uploads/beet/'),
        ),
        migrations.AlterField(
            model_name='others',
            name='image',
            field=models.ImageField(upload_to='uploads/others/'),
        ),
        migrations.AlterField(
            model_name='plythickness',
            name='image',
            field=models.ImageField(upload_to='uploads/ply/'),
        ),
    ]
