# Generated by Django 3.0.8 on 2020-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200702_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beetname',
            name='image',
            field=models.ImageField(upload_to='beet/'),
        ),
        migrations.AlterField(
            model_name='others',
            name='image',
            field=models.ImageField(upload_to='others/'),
        ),
        migrations.AlterField(
            model_name='plythickness',
            name='image',
            field=models.ImageField(upload_to='ply/'),
        ),
    ]
