# Generated by Django 3.0.8 on 2020-07-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200702_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beet',
            name='godown',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beet',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='others',
            name='godown',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plywood',
            name='godown',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plywood',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plywood',
            name='thickness',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterproof',
            name='godown',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterproof',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterproof',
            name='thickness',
            field=models.CharField(max_length=50),
        ),
    ]
