# Generated by Django 3.0.8 on 2020-07-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200704_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plywood',
            name='godown',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plywood',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plywood',
            name='thickness',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterproof',
            name='godown',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterproof',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='waterproof',
            name='thickness',
            field=models.CharField(max_length=50),
        ),
    ]
