# Generated by Django 3.0.8 on 2020-07-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20200704_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beet',
        ),
        migrations.DeleteModel(
            name='BeetName',
        ),
        migrations.DeleteModel(
            name='BeetSize',
        ),
        migrations.DeleteModel(
            name='Others',
        ),
        migrations.DeleteModel(
            name='OthersName',
        ),
        migrations.DeleteModel(
            name='Plywood',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='waterproof',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='waterproof',
            name='size',
        ),
        migrations.RemoveField(
            model_name='waterproof',
            name='thickness',
        ),
        migrations.DeleteModel(
            name='Godown',
        ),
        migrations.DeleteModel(
            name='PlySize',
        ),
        migrations.DeleteModel(
            name='PlyThickness',
        ),
        migrations.DeleteModel(
            name='WaterProof',
        ),
    ]
