# Generated by Django 3.0.8 on 2020-07-05 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20200704_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beet',
            name='godown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Godown'),
        ),
        migrations.AlterField(
            model_name='beet',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BeetName'),
        ),
        migrations.AlterField(
            model_name='beet',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BeetSize'),
        ),
        migrations.AlterField(
            model_name='others',
            name='godown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Godown'),
        ),
        migrations.AlterField(
            model_name='others',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.OthersName'),
        ),
    ]
